name: BINGO WORKFLOW

on:
  push:
    branches:
      - githubActions_improvement

jobs:
  syntax_check_job:
    name: syntax_check_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: githubActions_improvement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
    outputs:
      job-status: ${{ job.status }}
  test_execution_job:
    name: test_execution_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: |
          npm install
          npm install jest
          npm test
    outputs:
      job-status: ${{ job.status }}
  build_statics_job:
    name: build_statics_job
    runs-on: ubuntu-latest
    needs: [syntax_check_job, test_execution_job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run buildDev
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./dist
    outputs:
      job-status: ${{ job.status }}
  deploy_job:
    runs-on: ubuntu-latest
    needs: build_statics_job
    steps:
      - name: artifact download
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: surge_deploy
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: vicnx_bingo.surge.sh
          project: .
          login: ${{ secrets.SURGE_EMAIL }}
          token: ${{ secrets.SURGE_TOKEN }}
    outputs:
      job-status: ${{ job.status }}
  notification_job:
    name: notification_job
    runs-on: ubuntu-latest
    needs: [syntax_check_job, test_execution_job, build_statics_job, deploy_job]
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Email
        uses: ./.github/actions/notification_action
        with:
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          send_email: ${{ secrets.SEND_EMAIL }}
          send_pass: ${{ secrets.SEND_PASS }}
          syntax_check_job: ${{needs.syntax_check_job.outputs.job-status}}
          test_execution_job: ${{needs.test_execution_job.outputs.job-status}}
          build_statics_job: ${{needs.build_statics_job.outputs.job-status}}
          deploy_job: ${{needs.deploy_job.outputs.job-status}}
  update_readme_job:
    name: update_readme_job
    runs-on: ubuntu-latest
    needs: deploy_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set new line readme
        run: |
          echo -e "\nUltima versión desplegada el día: `date`" >> README.md
      - name: Push changes to repository
        run: |
          git config user.name vicnx
          git config user.email andanivicente@gmail.com
          git add .
          git commit -m "Actualizado readme con ultima fecha de deploy!"
          git push origin githubActions_improvement
